name: tiki_sdk_flutter
description: A package for adding TIKI's decentralized infrastructure to Flutter projects. Add tokenized data ownership, consent, and rewards to your app in minutes.
version: 0.0.24
homepage: https://mytiki.com
documentation: https://docs.mytiki.com
repository: https://github.com/tiki/tiki-sdk-flutter
issue_tracker: https://github.com/tiki/tiki-sdk-flutter/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  path_provider: ^2.0.11
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12
  tiki_sdk_dart: ^0.0.18

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  module:
    androidX: true
    androidPackage: com.mytiki.tiki_sdk_flutter
    iosBundleIdentifier: com.mytiki.tiki-sdk-flutter
