name: Publish AARs

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version From Pubspec
        id: tag
        run: |
          export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Checkout current tag
        run: |
          git checkout ${{steps.tag.outputs.version }}

      - name: Checkout current tag
        run: git checkout ${{steps.tag.outputs.version }}

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: 'Set up Java 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Remove unused dependencies'
        run: |
          perl -i -p0e 's/  integration_test:\n    sdk: flutter//s' pubspec.yaml
          perl -i -p0e 's/permission_handler: \^10.2.0//s' pubspec.yaml
          perl -i -p0e 's/package_info_plus: \^3.0.3//s' pubspec.yaml

      - name: 'Flutter Pub Get'
        run: |
          flutter pub get

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar

      - name: 'Append publish.gradle script'
        run: |
          cat publish.gradle >> .android/build.gradle

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar --no-debug --no-profile --build-number ${{steps.tag.outputs.version }}
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}